### ISSUE TITLE
Data Entry/Sample Location - missing sites

### ISSUE THREAD

**Issue by mzperry** [dancrocker/BRCWQDM#3]
Several midreach sites missing.  Identified Center Brook, Centerville Brook, WestR@Mendon Rd specifically.  Will resolve with updated site list (issue #2)

**Comment by dancrocker** [comment]
Any missing sites need to be added to the sites table in the database. Get me the missing sites and I will add them.

**Comment by mzperry** [comment]
Attached a file that cross references the site names used in the interim data entry form with BRC Code.
[location_xref_entry-compare.xlsx](https://github.com/dancrocker/BRCWQDM/files/3447569/location_xref_entry-compare.xlsx)

1. No need to adjust site names.  This will probably be addressed later and infinitely into the future.
2. Sites not highlighted are missing from data entry list.
3. Yellow highlighted sites are in the list.
4. Orange-ish highlighted site is a typo.

Strangely there is one on the list that I don't have as active: A-07-09-010  O'Hara Brook.
I added a new site in RI: C-02–03-045.  I have no other info on it.
The other info for the sites is in the master list.  I'm not sure how the table was created so I'm not sure the best way for you to update it with all the fields.  I can support in any way.

**Comment by dancrocker** [comment]
Added all sites that were missing from the attached spreadsheet.  I also added a "Status" field to the sites table so that inactive sites can be culled from the site selection dropdown. Current status of sites needs to be finalized in database. I can add the RI site, but it would be better to wait until there is a waterbody name and a site name.
