### ISSUE TITLE
Data Entry - comments vs other

### ISSUE THREAD

**Issue by mzperry** [dancrocker/BRCWQDM#9]
This one is for thought/discussion.
We historically have a blurred policy toward comments that I sought to remedy but in hindsight failed to think through completely.  So, some thoughts:

1. other is other, a selection and not a comment.
2. I think you adequately addressed the distinction between field and FC comments.  I didn't test cases with multiple comments from both sources.
3. I think that having some parameters with dedicated comments and some with only comments in the Other Sample Information section seems inconsistent.  Why not one or the other.  Put all the comments in the OSI section?  A button at each parameter linking to the comments?  One of the ineffeciencies I sought to fix was that i had to scroll away from the parameter to add a comment when a dedicated field didn't exist.  BTW this is just as likely as having a comment for the dedicated fields.  Then scrolling back to find where I left off.  Breaks the flow. Solution is to have comments for each parameter right there but this is crazy cluttered.  I think I can live with going to the OSI section knowing I have a parameter-linked place to put the comment.  But why not do it consistently for all parameters.  I'd like to propose this to Susan if you agree but any other elegant ways to improve my slumber over the topic would be appreciated.

**Comment by dancrocker** [comment]
I can put a add comment button in each data entry section, this way you don't need to leave that section to add a comment. I could also remove parameter specific comments, thereby creating a uniform method of adding comments. Comments boxes should not be hard linked to each parameter because this would cause issues in the case of multiple comments by the same or different people. There is no way to know _a-priori_ the number of comments that there could be. Does this solution sound ok? We can discuss other ideas as well.

**Comment by dancrocker** [comment]
I think this has been addressed with a comment button in each data entry section as well as OSI AND on the staged data and submitted data pages. We can reopen issue if another option works better, but I will close for now.
